### ISSUE TITLE
Presets

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#11]
¿En las resistencias de los leds? Polarizan todo el circuito

**Comment by nachocarballeda** [comment]
??? no entendi

**Comment by anojo** [comment]
@nachocarballeda Iván me había preguntado dónde podía convenir poner presets para las resistencias de valor sensible. Después dijo que quede para después. Supuse que en las resistencias en los leds, que regulan las fuentes de corriente de la 1era etapa, pero no está definid.

**Comment by anojo** [comment]
Me habían comentado que había pines en el PCB para probar cosas y que les viniero bárbaro el semestre pasado. ¿Dónde quedan esos pines en el circuito?
