### ISSUE TITLE
Zobel

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#12]
Parece que sí era importante.
Según Douglas, 10 ohms y 0.1uF va bien siempre y fuck it.

**Comment by anojo** [comment]
La escribe "ZoEbel" en el mail

**Comment by igpollitzer** [comment]
Agregué la red de Zobel. Dejo este inconveniente abierto, por si quieren dejarlo hasta que lo agreguen en el informe. Sino, cierrenlo.

**Comment by anojo** [comment]
Claro que queda abierto. No le consultamos a Fede, no lo agregamos en el circuito.

**Comment by anojo** [comment]
Además, por loq ue veo en el circuito del clase G del Douglas, además de esa RC tiene un RL paralelo a la salida

**Comment by anojo** [comment]
Aparentemente, es el RC lo que se llama Zobel. Y el LR es para "aislar al amplificador de capacidad de carga". "Un componente de 15-20 vueltas de diámetro 1 pultada debería funcionar bien. El valor de la inductancia no es para nada crítico para la estabilidad"

**Comment by anojo** [comment]
El inductor tiene que ser de aire para tener menos distorsión. Los valores de L suelen andar en 1-7uH.
