### ISSUE TITLE
Cálculo y justificación de las decisiones de diseño

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#16]
Valores de componentes, tipos, tecnologías, subcircuitos, lablab.

**Comment by nachocarballeda** [comment]
esto ya esta.. ¿le mando los datasheets de los "subcircuitos"  ??

**Comment by anojo** [comment]
Meter los datasheets en el informe de avance sería demasiado,  jaja

**Comment by nachocarballeda** [comment]
entonces cerramos esto?

**Comment by anojo** [comment]
yo no lo cerraría, me parece que es uno de esos puntos donde mienrtas más mejor. Dejémoslo para lo último.

**Comment by anojo** [comment]
Faltan, al menos, cuestiones de la etapa de salida (¿para qué es ese capacitorr? Una versus otra opción respecto de las resistencias en los emisores de los drivers de la parte interna. Chamullo diodo schohcsocohty, ...)
