### ISSUE TITLE
Lista de componentes

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#17]
Tabla con

Nombre en el esquemático |  valor/modelo  | Tolerancia (?) | Potencia (?) | Tecnología/whatever

**Comment by anojo** [comment]
Aclarar en dónde se usa SMD. Ver si hace falta incluir tooodo, disipadores etc

**Comment by anojo** [comment]
¿Tolerancias?

**Comment by nachocarballeda** [comment]
listo,agregadas tolerancias no entran mas columnas.
