### ISSUE TITLE
Especificaciones: sensibilidad

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#32]
La sensibilidad debe especificarse a qué potencia - carga específica (pág 3)

**Comment by anojo** [comment]
¿No se entiende que si especificamos que el ampli trabaja con 8 ohms, la sensibilidad y todo lo demás, por defecto, es con 8 orms de carga? Sigh

**Comment by igpollitzer** [comment]
Suspirás en inglés? Es lo que hay, viejo, respetar la nomenclatura.

**Comment by anojo** [comment]
Bueno, cambio 1V RMS a 1V RMS @ 8\Omega.  ¿Valdrá la pena también especificar en corto, o a 2/4 ohms?
