### ISSUE TITLE
Realimentación

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#33]
Poner qué tipo de realimentación utilizan, es decir, qué se suma y qué se muestrea

**Comment by anojo** [comment]
Ok, esto es factible. Mirar el circuito, ver todas las realimentaciones, globales y locales que se encuentren, que estén mencionadas ena lgna  parte del informe, y donde lo estén, que se mencione si son serie-paralelo (sumo tensión muestreo tensión), serie-serie (...), etc.

**Comment by igpollitzer** [comment]
Yo asumo que la respuesta, es la del issue siguiente.
