### ISSUE TITLE
Modelo como op-amp realimentado

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#34]
Analicen el circuito como si fuera un Op.Amp. realimentado, viendo las Zin, las Zo, etc, todo tal cual lo vieron en la 1era parte de la materia, incluído el SR, la compensación etc.

**Comment by anojo** [comment]
Ok, no pusimos ningún diagrama con el triangulito realimentado. Pero slew rate, compensación, no estoy seguro de lo que quiere. ¿Ustedes?

**Comment by igpollitzer** [comment]
asumo que quiere que hagamos el triangulito, con el cuadrado de realimentación abajo, midiendo tensión y sumando tensión (paralelo/serie) eso modifica las impedancias de entrada y salida. No se que es lo que quiere con el SR y la compensación, salvo que sea hacer Ivas x Cmiller.

**Comment by anojo** [comment]
@igpollitzer pero el nodo de Miller está adentro del opamp, no veo cómo se puede mencionar con ese modelo

**Comment by nachocarballeda** [comment]
![bob_cordell](https://cloud.githubusercontent.com/assets/9441622/11831383/083fe128-a38d-11e5-90bb-c92f8f97fa83.png)
Bob Cordell  - Designing Audio Power Amplifiers

**Comment by igpollitzer** [comment]
Bueno, yo creo que esto ya está terminado. Hice el dibujito del opamp realimentado, hice el gráfico de Bode compensado, y el cálculo del Slew Rate. Todo Bertu-Style.
