### ISSUE TITLE
Punto #2.5: mail Fede

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#35]
Los análisis que hagan, deberían ser en base a los antecedentes que encontraron, es decir: plantear bloques o soluciones en base a circuitos modelos.

**Comment by anojo** [comment]
Huh?

**Comment by nachocarballeda** [comment]
Creo que quiere decir que si usas un ampli doble diferencial le expliques porque (esto se hizo), y 2doble le 2Vbe le expliques porque , y todo asi diciendo de donde sacaste la idea.
