### ISSUE TITLE
Antecedentes

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#38]
Ok, pero agreguen circuitos, notas de aplicación y otros esquemas demostrando que buscaron antecedentes de un Amp. Clase G

**Comment by nachocarballeda** [comment]
Ok, voy a agregar el clase G del Douglas Self y buscar algun comercial

**Comment by anojo** [comment]
El "buscar algún comercial" quedó inconcluso, ¿no?
