### ISSUE TITLE
Qué transistores para la 2da etapa

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#40]
¿Los que están u otros? Los que están, según los modelos de LTSpice, tiene la desventaja de que
- No son muy simétricos entre sí los NPN de los PNP
- Tienen  tensión de Early baja y por eso son "mala carga" el uno del otro. Esto sólo importaría para los EC. Anojo tiene que simular para saber cuánto importa.
- Quizá, un beta mejor estabilizaría un poco más la polarización. No me suena que esto sea importante.

**Comment by nachocarballeda** [comment]
Por ahora en la segundo etapa tenemos MPSA42 (NPN) y MPSA92 (PNP)
No entiendo eso de que "no son muy simetricos" , entiendo que uno es el complemento del otro.
El VCE es 300V  en ambos, ¿esto es poco?
