### ISSUE TITLE
Mejorar PCB

### ISSUE THREAD

**Issue by anojo** [nachocarballeda/gclass_amplifier#41]

**Comment by anojo** [comment]
¿Cómo se arma posta el tema de las redes de salida, zobel y la otra, con el inductor loco de 1 pulgada de diámetro?

**Comment by nachocarballeda** [comment]
@anojo Con alambre, lo dice en el Douglas S.

**Comment by anojo** [comment]
@nachocarballeda O sea, nada que ver con el PCB, ¿no?
